### ISSUE TITLE
运行失败，不知道为什么

### ISSUE THREAD

**Issue by tiddlerhxy** [YuZongYangHi/ansible-linux-monitor#1]
[root@tiddler ansible-custom-collection-tool]# python3 main.py  --host 192.168.1.10 --type local
 [WARNING]:  * Failed to parse /woke_home/ansible-custom-collection-tool/hosts with script plugin: Invalid empty host name provided:

 [WARNING]:  * Failed to parse /woke_home/ansible-custom-collection-tool/hosts with yaml plugin: Syntax Error while loading YAML.   mapping
values are not allowed here  The error appears to be in '/woke_home/ansible-custom-collection-tool/hosts': line 7, column 17, but may be
elsewhere in the file depending on the exact syntax problem.  The offending line appears to be:   def Group_list():                 ^ here

 [WARNING]:  * Failed to parse /woke_home/ansible-custom-collection-tool/hosts with ini plugin: /woke_home/ansible-custom-collection-
tool/hosts:4: Expected key=value host variable assignment, got: json

 [WARNING]: Unable to parse /woke_home/ansible-custom-collection-tool/hosts as an inventory source

 [WARNING]: No inventory was parsed, only implicit localhost is available

 run => 192.168.1.10
Traceback (most recent call last):
  File "main.py", line 310, in <module>
    transfer.run()
  File "main.py", line 133, in run
    return self.run_complete()
  File "main.py", line 177, in run_complete
    self.all_action(command, method, task_id, name)
  File "main.py", line 182, in all_action
    response = self.ad_hoc(hosts=i, module="shell", command=command)
  File "main.py", line 202, in ad_hoc
    response = self.ansible.run(host_list=hosts, moduls=module, _args=command)
  File "/woke_home/ansible-custom-collection-tool/api.py", line 93, in run
    stdout_callback=callback,
TypeError: __init__() got an unexpected keyword argument 'options'
[root@tiddler ansible-custom-collection-tool]#

**Comment by YuZongYangHi** [comment]
版本问题
